metadata:
  title: 'ChiroTraits: A Global Database for Bat Functional Traits'
  description: "A global database of bat functional trait data"
  doi: unknown
  structure_URI: https://github.com/RobertoRuizR/chirotraits.build
  geo_location:
    geo_location_place: Worldwide
    geodetic_datum: EPSG:4326
  language: en
  related_identifiers:
  - related_identifier_type: url 
    identifier: https://github.com/RobertoRuizR/chirotraits.build
    relation_type: Compiles
    resource_type: dataset
  - related_identifier_type: doi
    identifier: .na
    relation_type: isCitedBy
    resource_type: publication-article  
  - related_identifier_type: doi
    identifier: .na
    relation_type: isVersionOf
    resource_type: dataset
  references: "**publication associated with dataset"
  publisher: unknown
  publication_year: unknown
  publication_date: unknown
  license:
    rights: CC-BY-4.0    
    rights_holder: Ruiz-Ramírez, Roberto Antonio
    rights_URI: https://creativecommons.org/licenses/by/4.0/
    description: Under this license, the material can be copied and redistributed in any medium or format. It can be remixed, transformed, and built upon for any purpose, even commercially. Re-users must give appropriate credit, provide a link to the license, and indicate if changes were made. Re-users may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
  creators: 
  - last_name: Ruiz-Ramírez
    given_name: Roberto Antonio
    ORCID: 0000-0002-9814-092X
    affiliation: Evolutionary Macroecology Lab, Posgrado en Ciencias, Instituto de Ecología, A. C., Xalapa, Veracruz, México
  -  contributors: .na
