metadata:
  title: ChiroTraits
  description: A global database for bat functional trait data
  doi: unknown
  structure_URI: https://github.com/RobertoRuizR/chirotraits.build
  geo_location:
    geo_location_place: Worldwide
    geodetic_datum: EPSG:4326
  language: en
  related_identifiers:
  - related_identifier_type: url 
    identifier: https://github.com/RobertoRuizR/chirotraits.build
    relation_type: Compiles
    resource_type: dataset
  - related_identifier_type: doi
    identifier: .na
    relation_type: isCitedBy
    resource_type: publication-article  
  - related_identifier_type: doi
    identifier: .na
    relation_type: isVersionOf
    resource_type: dataset
  references: "**publication associated with dataset"
  publisher: unknown
  publication_year: unknown
  publication_date: unknown
  license:
    rights: ODC Attribution License (ODC-By)    
    rights_holder: Ruiz-Ramírez, Roberto Antonio
    rights_URI: http://opendatacommons.org/licenses/by/1.0/
    description: The Open Data Commons Attribution License is a license agreement intended to allow users to freely share, modify, and use this Database subject only to the attribution requirements set out in Section 4.
  creators: 
  - last_name: Ruiz-Ramírez
    given_name: Roberto Antonio
    ORCID: 0000-0002-9814-092X
    affiliation: Evolutionary Macroecology Lab, Posgrado en Ciencias, Instituto de Ecología, A. C., Xalapa, Veracruz, México
  -  contributors: .na
